### ISSUE TITLE
Bare URL can show empty screen

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#93] opened 2017-05-09 16:57 UTC
It seems like the staging site is still using `ds=1` as the default dataset even if no dataset 1 exists, resulting in an empty page. Ideally we default to using the lowest existing dataset index.

**Comment by openjck** [comment] 2017-05-09 17:03
Is this a dupe of #82?

**Closed** 2017-05-10 14:27 UTC
Labels: in progress
