### ISSUE TITLE
Show how many people are in each population

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#155] opened 2017-06-29 17:28 UTC
Show a client count for each population. Among other things, this will help the experimenter verify that the number of people in the population matches their expectations. It wouldn't be a live count, but it sounds like this should be fine as long as we're clear that it's not a live count.

**Comment by robhudson** [comment] 2017-06-29 18:19
We have a count of per metric pings.

@sunahsuh Is this something we'd need to add upstream for the overall experiment and populations? Possible?

**Comment by sunahsuh** [comment] 2017-06-29 20:09
It's possible (and not hard) but I'll need to sync up with @robhudson about what format this should take

**Comment by openjck** [comment] 2017-07-28 21:36
This should be possible now that the back-end has landed

**Comment by openjck** [comment] 2017-08-07 20:21
I'll also take a look at this one this week. I got sidetracked by [Ensemble](https://github.com/openjck/ensemble) but it should be easy enough.

**Comment by openjck** [comment] 2017-08-08 16:34
It sounds like this is the same as #190. Or am I mistaken?

**Comment by robhudson** [comment] 2017-08-08 16:48
> It sounds like this is the same as #190. Or am I mistaken?

No, #190 is using `numObs`, which is per metric and a count of the pings that contained that metric.

I believe what this bug is requesting is the number of pings and number of clients for each branch (and subgroup when that gets added) overall.

**Comment by robhudson** [comment] 2017-08-08 16:50
This data is currently in the API under the `/datasets/` URL. For each population there is a `total_pings` and `total_clients` counts.

**Comment by rafrombrc** [comment] 2017-08-08 18:22
Closing as a duplicate of #179.

**Closed** 2017-08-08 18:23 UTC
