### ISSUE TITLE
`.legend` and the "show data for this series" slider should have same ordering

### ISSUE THREAD

**Issue by gregglind** [mozilla/experiments-viewer#113] opened 2017-05-15 14:09 UTC
Claim:  `.legend` and the "show data for this series" slider should have same ordering

Right now, `.legend` is **control first**, but the "show this series" sliders are **pure alpha**.  They should be the same.

**Comment by openjck** [comment] 2017-05-15 18:40
Sounds like a dupe of #97. It's been fixed but not yet pushed to production. We're pushing it to production now.

**Closed by openjck** 2017-05-15 18:40 UTC
