### ISSUE TITLE
Add current sample & client  count to the UI

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#179] opened 2017-07-24 19:06 UTC
The UI should show the current sample count (i.e. the number of samples that have been processed that are reflected in the graphs that are being displayed) and the current client count (i.e. the number of unique client ids that have been extracted from those samples), both by cohort and in total for the experiment. The 'by cohort' values are available from the API, they can be summed to get the totals.

**Comment by openjck** [comment] 2017-07-26 17:41
Is the current sample count the same as #155 or is that something else?

**Comment by robhudson** [comment] 2017-07-26 17:50
I don't believe so... sample count would be how many people we expect to be in the whole experiment. #155 is about showing how many people are in each population, the sum of which might equal expected sample size assuming all the data has been collected.

**Comment by robhudson** [comment] 2017-07-31 19:11
I looked into this last week. The Normandy API does not have an absolute value for expected sample size. What they do have is `stableSample` that is a percentage of the population based on the other filters. To come up with an actual number we'd have to estimate the size of the population given the other filters and take the percentage of that.

**Comment by rafrombrc** [comment] 2017-08-08 18:14
Punting on the expected sample size piece for now (and possibly forever). Leaving the important piece of showing the current sample count for the entire experiment and per cohort.

**Comment by rafrombrc** [comment] 2017-08-08 18:16
@robhudson tells me the per-cohort sample counts & client counts are available through the API, and the full experiment count would just be the total, now we need to add this to the front end.

**Comment by robhudson** [comment] 2017-08-08 18:18
I believe this has morphed into #155.

**Comment by openjck** [comment] 2017-08-17 20:31
#155 is currently marked as a duplicate of this. I'm not sure I understand what the goal of this issue is any more. Can someone provide an up-to-date requirement?

**Closed** 2017-08-23 19:41 UTC
Labels: ready
