### ISSUE TITLE
Hover dots don't move (and hover text doesn't update) for charts in Experiment 2

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#46] opened 2017-04-20 17:36 UTC
### Steps to reproduce

1. Load [this page](http://localhost:8000/?ds=2&metrics=ALL&scale=linear&sg=ALL&showOutliers=false)
2. Hover over a chart

### Actual result

The hover dots stay at the bottom-left and the hover text doesn't update

### Expected result

The hover dots move with the mouse and the hover description is updated along the way

**Comment by rafrombrc** [comment] 2017-04-27 17:20
We're pretty sure this is caused by the same underlying issue as #37, moving this to blocked and hopefully this will be closed when that issue is resolved.

**Comment by rafrombrc** [comment] 2017-05-01 18:34
Turns out to not be caused by #37, but we've verified that it only happens on graphs which use non-categorical linear scale.

**Comment by rafrombrc** [comment] 2017-05-02 17:55
Current hypothesis is that this is caused by poorly formed fixture data, which will likely rarely or never happen in the real world. @robhudson is currently working on #78 which will reshape some of the fixture data and hopefully resolve this issue (or at least confirm our hypothesis that the data shape is the problem).

**Comment by spasovski** [comment] 2017-05-09 15:04
The core problem seems to be with linear scales on the x-axes when they are coming in descending order from the API endpoint. Think [0,1,2,3,4] vs [4,3,2,1,0]. Ideally the front-end would be able to deal with unsorted arrays but it currently doesn't (also part of the reason why ordinal scales are fine). Apparently descending order arrays won't happen with the real data. I am personally interested in cleaning up the way we generate charts (it's not terrible but does have some cruft from DV) at which point this may also become addressed.

**Comment by rafrombrc** [comment] 2017-05-09 17:29
Okay, we've confirmed that this issue only happens when the x-axis values come down from the API unsorted. We've already updated the API so that the values will always come down sorted, closing this issue.

**Closed** 2017-05-09 17:29 UTC
Labels: blocked
